### ISSUE TITLE
Hi, any interest to  reimplement CLONE together?

### ISSUE THREAD

**Issue by GuangChen2016** [CODEJIN/HierSpeech#3]
Hi, I found that you are reimplementing HierSpeech, and I noticed that CLONE is another good end2end tts models, which  has none mispronunciation issues and performs more stable than VITS arrording to the paper, do you have any plans to reimplement it togethert?
Controllable and Lossless Non-Autoregressive End-to-End Text-to-Speech？https://arxiv.org/pdf/2207.06088.pdf

Thanks.

**Comment by dutchsing009** [comment]
Hierspeech is 10x times better than "CLONE", Hierspeech can do multi-speaker TTS ,voice conversion and Speaker Adaptation. While CLONE only does single-speaker, maybe the only advantage is it does 48khz , I see that Hierspeech can perform 48khz too, why not. Also from the paper it looks like they trained Vits for 500k only along with CLONE , and Vits needs Atleast 800-900k to shine. "CLONE" also still has slight hearable speech artifacts, if you are really looking for natural artifact-less TTS look into this , https://github.com/heatz123/naturalspeech

**Comment by CODEJIN** [comment]
Hi, @GuangChen2016 

I am interested in the model you mentioned, but I am currently employed and in a position where collaboration with external personnel is restricted. I appreciate your proposal, but unfortunately, collaboration seems to be difficult. Thank you for introducing me to the good model, and I apologize for any inconvenience caused by the limitation on collaboration.

Best regards,

Heejo

**Comment by CODEJIN** [comment]
Hi, @dutchsing009 

Thank you for introducing the good model. Based on the implemented code, it seems that using ground-truth based duration is recommended as a priority. However, have you ever tested it with the `use_gt_duration=False` condition? If possible, I am considering exploring the option of using external aligners as little as possible.

Best regards,

Heejo

**Comment by dutchsing009** [comment]
Hello Mr. @CODEJIN I hope you are doing okay. Well In general, using ground-truth based duration can result in more accurate and natural-sounding speech output because the model is trained to generate speech with durations that match those of the reference speech segments. However, this approach requires having high-quality reference speech data with accurate duration information, which may not always be available.
2-On the other hand, using "use_gt_duration=False" means that the model is not explicitly trained to match the duration of reference speech segments. Instead, the model may learn to predict duration based on other features of the input text. This approach may be more flexible and better suited to situations where accurate duration information is not available or difficult to obtain. so no I still didn't try use_gt_duration=False condition but I will soon and will tell you if it succeeded . Some say that it is recommended as a default. This is because TTS systems are designed to be adaptable to different input texts, and relying on fixed durations may not always produce the best results. In addition, when dealing with spontaneous speech or unaligned data, ground-truth durations may not be available or accurate.

**Comment by CODEJIN** [comment]
Hi, @dutchsing009

Thank you for your opinion on NaturalSpeech. After analyzing the code provided in the link, I would like to perform some verifications.
And, as for XaioiceSing2, it would be better to leave any issues related to it on the corresponding XaioiceSing2 platform rather than here.

Best regards,

Heejo
